### PR TITLE
Add EditorConfig

### PR DESCRIPTION
**Pull request by rawkode**
Nice and simple, but super useful :+1:

### CODE REVIEW

**Comment by agnesjang98** [comment]
Hi @rawkode! Could you clarify what this EditorConfig is for?

**Comment by rawkode** [comment]
Every repository should have an editorconfig file:

```
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.
```

https://editorconfig.org/

**Comment by agnesjang98** [comment]
Hi @rawkode, I will take a look at this! Thank you for your contribution.

**Comment by thinkingserious** [comment]
Hello @rawkode!

Thanks for the contribution! Could you please take a moment to [sign our CLA](https://cla.sendgrid.com/sendgrid/dx-mobile?pullRequest=13) so that we may merge your work?

With Best Regards,

Elmer

**Comment by rawkode** [comment]
Done

**Comment by thinkingserious** [comment]
Hello @rawkode,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
